services:
  collector:
    build: .
    container_name: bsky_collector
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - PYTHONPATH=/app
    volumes:
      - .:/app  # Synchronise votre code local avec le conteneur
    command: python -m src.collect.main
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: content-monitoring-db-1
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432" # Permet d'accéder à la DB depuis Windows (localhost:5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Stocke les données sur votre disque dur
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Déclare le volume pour la persistance des données